export const texts = {
    settings: 'settings',
    eMail: "email",
    password: "password",
    colorTheme: "colorTheme",
    dark: "dark",
    light: "light",
    language: "language",
    english: "english",
    turkish: "turkish",
    signOut: "signOut",
    login: "login",
    username: "username",
    signUp: "signUp",
    appname: "appname",
    homeTitle: "homeTitle",
    alert: "alert",
    alert1: "alert1",
    alert2: "alert2",
    season: "season",
    episode: "episode",
    airDate: "airDate",
    characters: "characters",
    episodeTitle: "Episode",
    characterTitle: "Character",
    status: "status",
    species: "species",
    gender: "gender",
    type: "type",
    origin: "origin",
    location: "location",
};

export const english = {
    [texts.settings]: "Settings",
    [texts.eMail]: "E-Mail",
    [texts.password]: "Password",
    [texts.colorTheme]: "Color Theme",
    [texts.language]: "Language",
    [texts.english]: "English",
    [texts.turkish]: "Türkçe",
    [texts.login]: "Login",
    [texts.dark]: "Dark Mode",
    [texts.light]: "Light Mode",
    [texts.signOut]: "Sign Out",
    [texts.username]: "Username",
    [texts.signUp]: "Sign Up",
    [texts.appname]: "Episodes and Characters",
    [texts.homeTitle]: "Episodes",
    [texts.alert]: "Warning",
    [texts.alert1]: "Please fill in all the required fields.",
    [texts.alert2]: "Please check your e-mail address.",
    [texts.season]: "Season: ",
    [texts.episode]: "Episode: ",
    [texts.airDate]: "Air Date:",
    [texts.characters]: "Characters",
    [texts.episodeTitle]: "Episode",
    [texts.characterTitle]: "Character",
    [texts.status]: "Status: ",
    [texts.species]: "Species: ",
    [texts.gender]: "Gender: ",
    [texts.type]: "Type: ",
    [texts.origin]: "Origin: ",
    [texts.location]: "Location: ",
};

export const turkish = {
    [texts.settings]: "Ayarlar",
    [texts.eMail]: "E-Mail",
    [texts.password]: "Şifre",
    [texts.colorTheme]: "Renk Modu",
    [texts.language]: "Diller",
    [texts.english]: "English",
    [texts.turkish]: "Türkçe",
    [texts.login]: "Giriş Yap",
    [texts.dark]: "Karanlık Mod",
    [texts.light]: "Aydınlık Mod",
    [texts.signOut]: "Çıkış Yap",
    [texts.username]: "Kullanıcı Adı",
    [texts.signUp]: "Kayıt Ol",
    [texts.appname]: "Bölümler ve Karakterler",
    [texts.homeTitle]: "Bölümler",
    [texts.alert]: "Uyarı",
    [texts.alert1]: "Lütfen tüm alanları doldurun.",
    [texts.alert2]: "Lütfen e-posta adresinizi kontrol edin.",
    [texts.season]: "Sezon: ",
    [texts.episode]: "Bölüm: ",
    [texts.airDate]: "Yayın Tarihi:",
    [texts.characters]: "Karakterler",
    [texts.episodeTitle]: "Bölüm",
    [texts.characterTitle]: "Karakter",
    [texts.status]: "Durum: ",
    [texts.species]: "Tür: ",
    [texts.gender]: "Cinsiyet: ",
    [texts.type]: "Tip: ",
    [texts.origin]: "Köken: ",
    [texts.location]: "Konum: ",
};